### ISSUE TITLE
Make encoders more reusable

### ISSUE THREAD

**Issue by saily** [amitbet/vnc2video#3]
When reusing and customizing encoders I'm limited though non exported functions or struct attributes. Example:

1. To overwrite command in `encoders.X264ImageEncoder` we must be able to set `cmd` in the struct `X264ImageEncoder` which is not allowed because it's not exported. See below's example: 
```golang

import (
    // ...
    "github.com/amitbet/vnc2video/encoders"
)

// ...

type Encoder struct {
	encoders.X264ImageEncoder
	quality       int
	present       string
	vcodec        string
	fileExt       string
}

func (enc *Encoder) Init(videoFileName string) {
        // works fine, as Framerate is exported
	if (enc.Framerate <= 0) {
		enc.Framerate = 12
	}

	cmd := exec.Command(
		enc.FFMpegBinPath,
		"-f", "image2pipe",
		"-vcodec", "ppm",
		"-r", strconv.Itoa(enc.Framerate),
		"-an", // no audio
		"-y",
		"-i", "-",
		"-vcodec", "libx264",
		"-preset", enc.present,
		"-crf", strconv.Itoa(enc.quality),
		videoFileName,
	)
        
	// XXX: This fails as input is not exported. Rename to Input
	enc.input, _ = cmd.StdinPipe()
	// XXX: This fails as cmd is not exported. Rename to Command
	enc.cmd = cmd
}
```

2. If I implement a whole new encoder with my own `Encode` function, I cannot reuse the `encodePPM` function in `encoders` package, as it's also not exported. 

Do you accept PRs on this?

**Comment by amitbet** [comment]
Sure, you can send me some PR to expose what you need,
What are you working on?

**Comment by saily** [comment]
I want to embed `encoders.X264ImageEncoder` in a custom encoder which adds additional stuff to the video as sound or text overlay. But since `cmd` and `input` are private, i'm not able to for example change the `exec.Cmd` for encoding.

So most simple way for now would be to export `cmd` as `Cmd` and `input` as `Input`.

**Comment by saily** [comment]
@amitbet why did you close this?
