### ISSUE TITLE
Use webrtc from golang pion project

### ISSUE THREAD

**Issue by joeblew99** [amitbet/vnc2video#5]
I was wondering about the idea of doing vnc but using P2P tech.

Pion webrtc is pretty solid now.

The mouse and keyboard stuff can be sent over the webrtc data channel.

Capturing the screen and pushing as a webrtc video channel is pretty easy.

Why ?
Higher equality as network is more efficient.
Less complicated than vnc

Also on the client it's easy to display the stream in a native window and detects the mouse and keyboard thanks to pion project.

So you don't have to run the client in a browser if you don't want to.

On the server it's easy to install the golang stuff as a service but not sure it will have rights to the desktop capture. So might have to run as a taskbar app.
Robotovgo golang project does all this for you

**Comment by amitbet** [comment]
What you are talking about sounds very similar to [screencat ](https://electronjs.org/apps/screencat)
only that it would be written in Go instead of electron, as you already mentioned - you also need a screenCap component (you could use ffmpeg, it is cross-platform, but requires special cap drivers per each OS), the benefit of using electron is that WebRTC along with screen capturing is already built in.
I would look at the chromium project to see what they took on for screen capturing... but I don't think that it can be done without some native code...
I tried using some cgo screen capturing code I found in some repo with minor fixes, but it is better fit for still frames than streaming video.

**Comment by joeblew99** [comment]
Hey @amitbet 
thanks for not discounting the idea and the comments.

Yeah i know the web approach and played around with it, but i think its easir and higher perf to do it with flutter and golang. 

For Webrtc between Desktop and Mobile and soon web) this works today
https://github.com/cloudwebrtc/flutter-webrtc-demo
The webrtc stuff is based on the Chromium code. It is embedded as a plugin inside the flutter GUI engine as far as i can see.
It can also do screen capture of your screen on mobile and stream it over webrtc btw now.
Its high perf too and easy to use !

About screen capture on Desktop side.
Getting screen capture working is just a flutter desktop plugin.
The Flutter Desktop version is built with golang and so we can tap into the stuff we need from golang code.
I was thinking of using this: https://github.com/go-vgo/robotgo It calls native i think.
Just need to capture the screen frames and transcode and push onto the webrtc stream.
There is tons of code to do that here:
https://github.com/pion/webrtc

I saw someone using pion with robotgo. Gotta find the repo again.

So you could share your screen to anyone else on Web, Desktop or Mobile with this architecture
Pretty cool. 

Mouse and keyboard stuff.
If you want to allow someone to interact with your desktop that your sharing ( which is what VNC is all about ) then getting the data can be done with robotgo i think. Then you stream that to the person on the other side ( the Viewer), and render the mouse cursor ( not hard with flutter).
Then we want to pick up the mouse and keyboard events from the VIewer ( not hard with fluttr at all) and then send them back to the Desktop stream and use robotgo to actually do them.
All this would go across the webrtc data channel.

**Comment by winwisely99** [comment]
I found this one: https://github.com/deluan/bring

Its gives you a GUI to the remote desktop and works on all desktops.
https://github.com/deluan/bring/tree/master/sample

Now i just need to work out how to integrate the video recording.
